# Generated by Django 2.2.5 on 2019-09-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
