# Generated by Django 2.2.5 on 2019-09-30 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190930_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='games_list',
            field=models.ManyToManyField(related_name='choices', to='app.Game'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='app.Game'),
        ),
    ]
