# Generated by Django 2.2.5 on 2019-09-30 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190930_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserDetail')),
            ],
        ),
    ]
