# Generated by Django 2.2.5 on 2019-09-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creation_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
